### ISSUE TITLE
NPE on empty db

### ISSUE THREAD

**Issue by SlavaChristin** [dbmaster/dbmaster-core#48]
java.lang.NullPointerException: null
	at com.branegy.dbmaster.connection.ConnectionProvider.activateDrivers(ConnectionProvider.java:230)
	at com.branegy.dbmaster.connection.ConnectionProvider.<init>(ConnectionProvider.java:68)
	at com.branegy.dbmaster.connection.ConnectionProvider.get(ConnectionProvider.java:61)
	at com.branegy.service.connection.impl.ConnectionServiceImpl.getDriverList(ConnectionServiceImpl.java:139)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:56)
	at com.branegy.service.base.impl.ServiceMethodInterceptor.invoke(ServiceMethodInterceptor.java:28)
	at com.branegy.service.connection.impl.ConnectionServiceImpl.getConnectionSlice(ConnectionServiceImpl.java:258)

**Comment by SlavaChristin** [comment]
drivers.ini should be renamed during installation
